### ISSUE TITLE
HTML5: boolean attribute is not generated correctly

### ISSUE THREAD

**Issue by fehmud** [madnificent/SEXML#3]
I am trying to generate this HTML5 code:

```
<select name="cars" multiple>
  <option value="volvo">Volvo</option>
  <option value="saab">Saab</option>
  <option value="opel">Opel</option>
  <option value="audi">Audi</option>
</select>
```

with this SEXML snippet:

```
(<:select :name "cars" :multiple t
                 (<:option :value "volvo")
                 (<:option :value "saab")
                 (<:option :value "opel")
                 (<:option :value "audi"))
```

But SEXML generates the following code, where the "multiple" attribute is not generated correctly:

```
<select multiple="T">
    <option value="volvo"></option>
    <option value="saab"></option>
    <option value="opel"></option>
    <option value="audi"></option>
</select>
```

Any thoughts?  Thanks.

**Comment by madnificent** [comment]
SEXML generates valid XML.  The multiple tag, without a value, is valid SGML (as used by HTML5), but it is not valid XML.  Luckily, the HTML5 workgroup allows you to expand the `<select multiple>` to `<select multiple="true">`.

In SEXML that could become:

```
(<:select :name "cars" :multiple "true"
  (<:option :value "volvo")
  (<:option :value "saab")
  (<:option :value "opel")
  (<:option :value "audi"))
```

Does that help you?

**Comment by fehmud** [comment]
Yes, it does.  Thanks for your quick reply.

**Comment by fehmud** [comment]
[deleted for clarity]

**Comment by fehmud** [comment]
[deleted for clarity]

**Comment by fehmud** [comment]
OK, I have found it.  According to the current HTML5 specification for boolean attributes: "If the attribute is present, its value must either be the empty string or a value that is an ASCII case-insensitive match for the attribute's canonical name, with no leading or trailing whitespace."  That means that you should write either `<select multiple="">` or `<select multiple="multiple">`. Indeed, both versions pass validation.  Hence, since SEXML is language-agnostic, it can't make a special case for HTML5.  Or could it provide a callback for such cases?

Thank you for your attention.

**Comment by madnificent** [comment]
Actually, SEXML was conceived to output valid XML, but it was also built to be extensible.  In theory, you could generate JSON instead of HTML by writing a different outputter.  We could use that to alter the output which is generally written.

I think this might be better suited in a contrib, but for the sake of the argument, assume the following is executed in the `sexml` package.

Each producer has its own layer.  We define that first:

```
(deflayer sexml-html5-producer (sexml-xml-producer))
```

We want to override the writing of the html5 attributes.  This uses the original outputter, but augments it when nil or t is supplied as the value for a keyword.

```
(defun format-html5-attrs (stream arg colonp atp &rest options)
  (declare (ignore colonp atp options))
  (format stream "~{~A~,^ ~}"
          (loop for (attr value) on arg by #'cddr
             collect
               (cond ((eq value nil)
                      "")
                     ((eq value t)
                      attr)
                     (t (format nil "~A=\"~A\""
                                (tag-attribute-content attr)
                                (tag-attribute-content value)))))))
```

Next we define the producer.  This is roughly the same as the standard XML producer, but it sends all attributes to format-html5-attrs in one go.  For the attributes it will call the previously defined function and, in contrast to the original implementation, it supplies all attribute key-value pairs to the formatter at once.

```
(define-layered-method entity-printer-forms
  :in-layer sexml-html5-producer
  (entity attr-var body)
  `(format nil ,(concatenate 'string
                             "<" (name entity) " ~/sexml::format-html5-attrs/"
                             (if (subelements-p entity) ">" "/>") ;; tag
                             (when (subelements-p entity)
                               "~{~/sexml::format-tag-body-content/~}") ;; content
                             (when (subelements-p entity)
                               (concatenate 'string "</" (name entity) ">")))
           ,@(if (null (subelements-p entity))
                 (list attr-var)
                 (list attr-var body))))
```

We can define a layer for our new output, basing ourself on standard-sexml.  It's not required as we can inline it, but it's probably prettier.

```
(deflayer sexml-html5 (sexml-html5-producer standard-sexml))
```

The following is likely in your package.  It's what you'd expect from it, but it uses our new layers (and thus the new functionality).

```
#+sbcl (declaim (sb-ext:muffle-conditions style-warning))
(eval-when (:compile-toplevel :load-toplevel :execute)
  (sexml:with-compiletime-active-layers (sexml::sexml-html5 sexml:xml-doctype)
    (sexml:support-dtd (asdf:system-relative-pathname :sexml "html5.dtd") :<7)))
#+sbcl (declaim (sb-ext:unmuffle-conditions style-warning))
```

If we then run the following in the repl:

```
(<7:html (<7:body (<7:input :multiple t :name "canhasmultiple")))
```

We get the output as you'd have wanted it to be.

```
"<html ><body ><input multiple name=\"canhasmultiple\"/></body></html>"
```

As an added bonus, nil works too.  So the examples could become:

```
(<7:select :name "cars" :multiple t
           (<7:option :value "volvo")
           (<7:option :value "saab")
           (<7:option :value "opel")
           (<7:option :value "audi"))
"<select name=\"cars\" multiple><option value=\"volvo\"></option><option value=\"saab\"></option><option value=\"opel\"></option><option value=\"audi\"></option></select>"

(<7:select :name "cars" :multiple nil
           (<7:option :value "volvo")
           (<7:option :value "saab")
           (<7:option :value "opel")
           (<7:option :value "audi"))
"<select name=\"cars\" ><option value=\"volvo\"></option><option value=\"saab\"></option><option value=\"opel\"></option><option value=\"audi\"></option></select>"
```

Does that help your use-case?

**Comment by fehmud** [comment]
Yes, it does.  I agree that such code should stay outside SEXML.

Thank you very much for your time and effort.

**Comment by madnificent** [comment]
I have pushed this code to the HTML5 contrib.
